import requests

r = requests.get('https://www.vox.com/2018/9/25/17901082/trump-un-2018-speech-full-text')

data = r.text

data = data[92005:117717]

data = data.replace('\n',' ')
data = data.replace('</p>',' ')
data = data.replace('</a>', ' ')
data = data.replace('<p id=', ' ')
data = data.replace('<a href="https://www.vox.com/world/2017/9/19/16332770/trump-unga-speech-north-korea-iran">', '')
data = data.replace('<a href="https://www.vox.com/policy-and-politics/2017/9/19/16333290/trump-full-speech-transcript-un-general-assembly">', '')
data = data.replace('"Qb42ol">', ' ')
data = data.replace('"RrkDg9">', ' ')
data = data.replace('"ehqHPE">', ' ')
data = data.replace('"cicwjR">', ' ')
data = data.replace('"F1i2LJ">', ' ')
data = data.replace('"CKhBXm">', ' ')
data = data.replace('"1JN4WY">', ' ')
data = data.replace('"a1fKja">', ' ')
data = data.replace('"uMK9dI">', ' ')
data = data.replace('"64m7Jf">', ' ')
data = data.replace('"gM44HV">', ' ')
data = data.replace('"q3GM7z">', ' ')
data = data.replace('"KGCi8L">', ' ')
data = data.replace('"KsUeUC">', ' ')
data = data.replace('"cR5RV5">', ' ')
data = data.replace('"YDEq81">', ' ')
data = data.replace('"Z6I5bq">', ' ')
data = data.replace('"u2riPc">', ' ')
data = data.replace('"Yx0P4B">', ' ')
data = data.replace('"npbK00">', ' ')
data = data.replace('"PmWmMj">', ' ')
data = data.replace('"5PzzoY">', ' ')
data = data.replace('"hyZJgK">', ' ')
data = data.replace('"n2wvR5">', ' ')
data = data.replace('"jAAkq5">', ' ')
data = data.replace('"FXgaQ3">', ' ')
data = data.replace('"rIO8UR">', ' ')
data = data.replace('"8zjfzm">', ' ')
data = data.replace('"j1YjtQ">', ' ')
data = data.replace('"DTq7Xx">', ' ')
data = data.replace('"HP7bJv">', ' ')
data = data.replace('"64m7Jf">', ' ')
data = data.replace('"GiwrL6">', ' ')
data = data.replace('"a7faPp">', ' ')
data = data.replace('"bFDksK">', ' ')
data = data.replace('"YQiJ1M">', ' ')
data = data.replace('"spVgTc">', ' ')
data = data.replace('"ATCHk0">', ' ')
data = data.replace('"GBwq44">', ' ') 
data = data.replace('"IXbqpy">', ' ')
data = data.replace('"YyHi6Q">', ' ')
data = data.replace('"Z7D9wR">', ' ')
data = data.replace('"MF6Aj5">', ' ')
data = data.replace('"BEZFrh">', ' ')
data = data.replace('"aofXQa">', ' ')
data = data.replace('"JaUr5K">', ' ')
data = data.replace('"I5B3we">', ' ')
data = data.replace('"fxkrxd">', ' ')
data = data.replace('"dvYzvh">', ' ')
data = data.replace('"qpJZur">', ' ')
data = data.replace('"GrpRT3">', ' ')
data = data.replace('"gmX2pq">', ' ')
data = data.replace('"kG57U3">', ' ')
data = data.replace('"ACghpr">', ' ')
data = data.replace('"6wgp7q">', ' ')
data = data.replace('"aAhymi">', ' ')
data = data.replace('"arUKY9">', ' ')
data = data.replace('"U032US">', ' ')
data = data.replace('"oNMPwE">', ' ')
data = data.replace('"HHfKGw">', ' ')
data = data.replace('"VyREAn">', ' ')
data = data.replace('"ho9d9B">', ' ')
data = data.replace('"cF26si">', ' ')
data = data.replace('"3TruLu">', ' ')
data = data.replace('"mg3pQw">', ' ')
data = data.replace('"gl0t4E">', ' ')
data = data.replace('"w5LkMz">', ' ')
data = data.replace('"PJ58ub">', ' ')
data = data.replace('"LoDnTZ">', ' ')
data = data.replace('"vbWlzm">', ' ')
data = data.replace('"64ZSXC">', ' ')
data = data.replace('"K4iZDx">', ' ')
data = data.replace('"l4j77s">', ' ')
data = data.replace('"oOzvaJ">', ' ')
data = data.replace('"nWbjqU">', ' ')
data = data.replace('"5fGqFK">', ' ')
data = data.replace('"YfDLjI">', ' ')
data = data.replace('"G97hic">', ' ')
data = data.replace('"BkmM5D">', ' ')
data = data.replace('"aCKAHN">', ' ')
data = data.replace('"EdgTnP">', ' ')
data = data.replace('"z5XIGd">', ' ')
data = data.replace('"JG31ve">', ' ')
data = data.replace('"LtvQ0U">', ' ')
data = data.replace('"U0le6t">', ' ')
data = data.replace('"wtVDOX">', ' ')
data = data.replace('"ifFWwQ">', ' ')
data = data.replace('"ygqENp">', ' ')
data = data.replace('"mD77Vc">', ' ')
data = data.replace('"TyBHek">', ' ')
data = data.replace('"TFia8t">', ' ')
data = data.replace('"mgVOrt">', ' ')
data = data.replace('"2LeMOG">', ' ')
data = data.replace('"vwedBc">', ' ')
data = data.replace('"YLkHwj">', ' ')
data = data.replace('"UirOEx">', ' ')
data = data.replace('"rmQW8I">', ' ')
data = data.replace('"D3FUVt">', ' ')
data = data.replace('"oeG0df">', ' ')
data = data.replace('"WPa6ga">', ' ')
data = data.replace('"uCDYdn">', ' ')
data = data.replace('"ADSChO">', ' ')
data = data.replace('"Aogf2Y">', ' ')
data = data.replace('"68hVhn">', ' ')
data = data.replace('"g9nuW5">', ' ')
data = data.replace('<', ' ')
data = data.replace('hr class="p-entry-hr" id="FWI34g">', '  ')
data = data.replace('"DjzFI7">', ' ')
data = data.replace(',', ' ')
data = data.replace('“', ' ')
data = data.replace('”', ' ')
data = data.replace('.', ' ')
data = data.replace('-–', ' ')
data = data.replace('(', ' ')
data = data.replace(')', ' ')
data = data.replace('’', ' ')
data = data.replace('\p', ' ')
data = data.replace('gov/briefings-statements/remarks-president-trump-73rd-session-united-nations-general-assembly-new-york-ny/">president', '')
data = data.replace('href="https://www', '')
data = data.replace('"npblvu">', '')
data = data.replace('class="c-entry-content">', '')
data = data.replace('div', '')
data = data.replace('/figure>', '')
data = data.replace('/span>', '')
data = data.replace('/cite>' ,'')
data = data.replace('images', '')
data = data.replace('moore/getty', '')
data = data.replace('cite>john', '')
data = data.replace('/figcaption>', '')
data = data.replace('"npblvu">', '')
data = data.replace('gov/briefings-statements/remarks-president-trump-73rd-session-united-nations-general-assembly-new-york-ny/">president', '')
data = data.replace('cite>john', '')
data = data.replace('<p id="nPBlvu"><a href="https://www.whitehouse.gov/briefings-statements/remarks-president-trump-73rd-session-united-nations-general-assembly-new-york-ny/">', '')
data = data.replace('<div class="c-entry-content">', '')

words = data.lower().split()

mydict = {}

for w in words:

  if w in mydict:

    mydict[w] += 1

  else:

    mydict[w] = 1

 
for k in sorted(mydict, key = mydict.__getitem__, reverse = True):

  print('%s: %s' %(k, mydict[k]))
